name = "The Pond"
author = "Different"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36462646f290cf7969b6ddddab2c98855f76c714485147fd17f0ba3e9f3d1fda"

[versions]
fabric = "0.16.4"
minecraft = "1.20.1"
