name = "The Pond"
author = "Different"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6810bddb9fac7fe4e431213affb7d13fd83a2ebdb0ae2a67187d07034dea7b46"

[versions]
fabric = "0.16.4"
minecraft = "1.20.1"
