name = "The Pond Server"
author = "Different"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bedcc040c84a818671ccfd2f55c654dfb3e35b92420424ecc2843d933d894b9"

[versions]
fabric = "0.16.4"
minecraft = "1.20.1"
